update keccak
Signed-off-by: Tiago Oliveira <tfaoliveira@gmail.com>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -8,11 +8,9 @@ CFLAGS ?=-Wall -Wextra -Wpedantic -Wvla -Werror -std=c99 \
 SRC :=$(abspath ../src/)
 BIN := \
  mlkem1024_amd64_avx2\
- pqcrystals_kyber1024_avx2
- # mlkem768_amd64_ref
- # mlkem768_amd64_avx2
- # pqcrystals_kyber768_ref
- # pqcrystals_kyber768_avx2
+ pqcrystals_kyber1024_avx2\
+ mlkem768_amd64_avx2\
+ pqcrystals_kyber768_avx2
  
 BIN :=$(addprefix bin/,$(BIN))
 BIN_CHECKSMALL :=$(addsuffix _checksumsmall,$(BIN))
@@ -31,21 +29,6 @@ default: run
 #-- build
 
 build: $(BIN)
-
-#--pq-crystals/kyber768/ref
-define CHECKSUM_RULE1
-bin/pqcrystals_kyber768_ref_checksum$(1): TESTING_LOOPS=$(2)
-bin/pqcrystals_kyber768_ref_checksum$(1): $(EXTERNAL)/pq_crystals_kyber/ref/lib/libpqcrystals_fips202_ref.so $(EXTERNAL)/pq_crystals_kyber/ref/lib/libpqcrystals_kyber768_ref.so __phony | bin/
-	$(CC) $(CFLAGS) \
-	  -o $$@ \
-	  -I $(EXTERNAL)/pq_crystals_kyber/ref/ \
-	  -DTESTING_LOOPS=$$(TESTING_LOOPS) \
-	  -DNAMESPACE=pqcrystals_kyber768_ref \
-	  checksums.c \
-	  -L$(EXTERNAL)/pq_crystals_kyber/ref/lib \
-	  -lpqcrystals_kyber768_ref -lpqcrystals_fips202_ref \
-	  -Wl,-rpath,$(EXTERNAL)/pq_crystals_kyber/ref/lib
-endef
 
 #--pq-crystals/kyber768/avx2
 define CHECKSUM_RULE2
@@ -90,13 +73,10 @@ bin/%_checksum$(1): __phony | bin/
 endef
 
 $(BIN):
-#$(eval $(call CHECKSUM_RULE1,small,8))
-#$(eval $(call CHECKSUM_RULE1,big,64))
-#$(eval $(call CHECKSUM_RULE1,giant,$(LOOPS)))
 
-#$(eval $(call CHECKSUM_RULE2,small,8))
-#$(eval $(call CHECKSUM_RULE2,big,64))
-#$(eval $(call CHECKSUM_RULE2,giant,$(LOOPS)))
+$(eval $(call CHECKSUM_RULE2,small,8))
+$(eval $(call CHECKSUM_RULE2,big,64))
+$(eval $(call CHECKSUM_RULE2,giant,$(LOOPS)))
 
 $(eval $(call CHECKSUM_RULE3,small,8))
 $(eval $(call CHECKSUM_RULE3,big,64))
@@ -108,13 +88,6 @@ $(eval $(call CHECKSUM_RULE4,giant,$(LOOPS)))
 
 #----------------------------------------------------------
 #-- build external
-
-#-- pqcrystals-kyber768-ref
-$(EXTERNAL)/pq_crystals_kyber/ref/lib/libpqcrystals_fips202_ref.so: __phony
-	$(MAKE) CFLAGS="-Wall -Wextra -Wpedantic -Wmissing-prototypes -Wredundant-decls -Wshadow -Wpointer-arith -O3 -fomit-frame-pointer -z noexecstack -mno-sse -mno-sse2 -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-avx -mno-avx2 -mno-avx512f" -C $(EXTERNAL)/pq_crystals_kyber/ref/ lib/libpqcrystals_fips202_ref.so
-
-$(EXTERNAL)/pq_crystals_kyber/ref/lib/libpqcrystals_kyber768_ref.so: __phony
-	$(MAKE) CFLAGS="-Wall -Wextra -Wpedantic -Wmissing-prototypes -Wredundant-decls -Wshadow -Wpointer-arith -O3 -fomit-frame-pointer -z noexecstack -mno-sse -mno-sse2 -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-avx -mno-avx2 -mno-avx512f" -C $(EXTERNAL)/pq_crystals_kyber/ref/ lib/libpqcrystals_kyber768_ref.so
 
 #-- pqcrystals-kyber768-avx2
 
@@ -143,12 +116,9 @@ $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_kyber1024_avx2.so: __phony
 
 run: $(BIN_OUT)
 	for t in small big giant; do \
-		# (cmp --silent bin/mlkem768_amd64_ref_checksum$$t.out bin/pqcrystals_kyber768_ref_checksum$$t.out \
-		#  && echo -n "OK - ") || echo -n "ERROR - "; \
-		# echo "bin/mlkem768_amd64_ref_checksum$$t.out / bin/pqcrystals_kyber768_ref_checksum$$t.out"; \
-		# (cmp --silent bin/mlkem768_amd64_avx2_checksum$$t.out bin/pqcrystals_kyber768_ref_checksum$$t.out \
-		#  && echo -n "OK - ") || echo -n "ERROR - "; \
-		# echo "bin/mlkem768_amd64_avx2_checksum$$t.out / bin/pqcrystals_kyber768_ref_checksum$$t.out"; \
+		(cmp --silent bin/mlkem768_amd64_avx2_checksum$$t.out bin/pqcrystals_kyber768_avx2_checksum$$t.out \
+		 && echo -n "OK - ") || echo -n "ERROR - "; \
+		echo "bin/mlkem768_amd64_avx2_checksum$$t.out / bin/pqcrystals_kyber768_avx2_checksum$$t.out"; \
 		(cmp --silent bin/mlkem1024_amd64_avx2_checksum$$t.out bin/pqcrystals_kyber1024_avx2_checksum$$t.out \
 		 && echo -n "OK - ") || echo -n "ERROR - "; \
 		echo "bin/mlkem1024_amd64_avx2_checksum$$t.out / bin/pqcrystals_kyber1024_avx2_checksum$$t.out"; \
