randomized input
Signed-off-by: Tiago Oliveira <tfaoliveira@gmail.com>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -9,8 +9,10 @@ SRC :=$(abspath ../src/)
 BIN := \
  mlkem768_amd64_ref\
  mlkem768_amd64_avx2\
+ mlkem1024_amd64_avx2\
  pqcrystals_kyber768_ref\
- pqcrystals_kyber768_avx2
+ pqcrystals_kyber768_avx2\
+ pqcrystals_kyber1024_avx2
 
 BIN :=$(addprefix bin/,$(BIN))
 BIN_CHECKSMALL :=$(addsuffix _checksumsmall,$(BIN))
@@ -30,7 +32,7 @@ default: run
 
 build: $(BIN)
 
-#--pq-crystals/kyber/ref
+#--pq-crystals/kyber768/ref
 define CHECKSUM_RULE1
 bin/pqcrystals_kyber768_ref_checksum$(1): TESTING_LOOPS=$(2)
 bin/pqcrystals_kyber768_ref_checksum$(1): $(EXTERNAL)/pq_crystals_kyber/ref/lib/libpqcrystals_fips202_ref.so $(EXTERNAL)/pq_crystals_kyber/ref/lib/libpqcrystals_kyber768_ref.so __phony | bin/
@@ -45,7 +47,7 @@ bin/pqcrystals_kyber768_ref_checksum$(1): $(EXTERNAL)/pq_crystals_kyber/ref/lib/
 	  -Wl,-rpath,$(EXTERNAL)/pq_crystals_kyber/ref/lib
 endef
 
-#--pq-crystals/kyber/avx2
+#--pq-crystals/kyber768/avx2
 define CHECKSUM_RULE2
 bin/pqcrystals_kyber768_avx2_checksum$(1): TESTING_LOOPS=$(2)
 bin/pqcrystals_kyber768_avx2_checksum$(1): $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_fips202_ref.so $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_fips202x4_avx2.so $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_kyber768_avx2.so __phony | bin/
@@ -60,7 +62,22 @@ bin/pqcrystals_kyber768_avx2_checksum$(1): $(EXTERNAL)/pq_crystals_kyber/avx2/li
 	  -Wl,-rpath,$(EXTERNAL)/pq_crystals_kyber/avx2
 endef
 
+#--pq-crystals/kyber1024/avx2
 define CHECKSUM_RULE3
+bin/pqcrystals_kyber1024_avx2_checksum$(1): TESTING_LOOPS=$(2)
+bin/pqcrystals_kyber1024_avx2_checksum$(1): $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_fips202_ref.so $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_fips202x4_avx2.so $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_kyber1024_avx2.so __phony | bin/
+	$(CC) $(CFLAGS) \
+	  -o $$@ \
+	  -I $(EXTERNAL)/pq_crystals_kyber/avx2/ \
+	  -DTESTING_LOOPS=$$(TESTING_LOOPS) \
+	  -DNAMESPACE=pqcrystals_kyber1024_avx2 \
+	  checksums.c \
+	  -L$(EXTERNAL)/pq_crystals_kyber/avx2 \
+	  -lpqcrystals_kyber1024_avx2 -lpqcrystals_fips202x4_avx2 -lpqcrystals_fips202_ref \
+	  -Wl,-rpath,$(EXTERNAL)/pq_crystals_kyber/avx2
+endef
+
+define CHECKSUM_RULE4
 bin/%_checksum$(1): TESTING_LOOPS=$(2)
 bin/%_checksum$(1): __phony | bin/
 	$(CC) $(CFLAGS) \
@@ -85,6 +102,10 @@ $(eval $(call CHECKSUM_RULE3,small,8))
 $(eval $(call CHECKSUM_RULE3,big,64))
 $(eval $(call CHECKSUM_RULE3,giant,$(LOOPS)))
 
+$(eval $(call CHECKSUM_RULE4,small,8))
+$(eval $(call CHECKSUM_RULE4,big,64))
+$(eval $(call CHECKSUM_RULE4,giant,$(LOOPS)))
+
 #----------------------------------------------------------
 #-- build external
 
@@ -106,14 +127,24 @@ $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_fips202x4_avx2.so: __phony
 $(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_kyber768_avx2.so: __phony
 	$(MAKE) CFLAGS="-Wall -Wextra -Wpedantic -Wmissing-prototypes -Wredundant-decls -Wshadow -Wpointer-arith -mavx2 -mbmi2 -mpopcnt -march=native -mtune=native -O3 -fomit-frame-pointer -z noexecstack -mno-avx512f" -C $(EXTERNAL)/pq_crystals_kyber/avx2/ libpqcrystals_kyber768_avx2.so
 
+#-- pqcrystals-kyber1024-avx2
+
+$(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_fips202_ref.so: __phony
+	$(MAKE) CFLAGS="-Wall -Wextra -Wpedantic -Wmissing-prototypes -Wredundant-decls -Wshadow -Wpointer-arith -mavx2 -mbmi2 -mpopcnt -march=native -mtune=native -O3 -fomit-frame-pointer -z noexecstack -mno-avx512f" -C $(EXTERNAL)/pq_crystals_kyber/avx2/ libpqcrystals_fips202_ref.so
+
+$(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_fips202x4_avx2.so: __phony
+	$(MAKE) CFLAGS="-Wall -Wextra -Wpedantic -Wmissing-prototypes -Wredundant-decls -Wshadow -Wpointer-arith -mavx2 -mbmi2 -mpopcnt -march=native -mtune=native -O3 -fomit-frame-pointer -z noexecstack -mno-avx512f" -C $(EXTERNAL)/pq_crystals_kyber/avx2/ libpqcrystals_fips202x4_avx2.so
+
+$(EXTERNAL)/pq_crystals_kyber/avx2/libpqcrystals_kyber1024_avx2.so: __phony
+	$(MAKE) CFLAGS="-Wall -Wextra -Wpedantic -Wmissing-prototypes -Wredundant-decls -Wshadow -Wpointer-arith -mavx2 -mbmi2 -mpopcnt -march=native -mtune=native -O3 -fomit-frame-pointer -z noexecstack -mno-avx512f" -C $(EXTERNAL)/pq_crystals_kyber/avx2/ libpqcrystals_kyber1024_avx2.so
+
 #----------------------------------------------------------
 #-- run
 
 run: $(BIN_OUT)
 	for t in small big giant; do \
-		(cmp --silent bin/mlkem768_amd64_ref_checksum$$t.out bin/mlkem768_amd64_avx2_checksum$$t.out \
-		 && echo -n "OK - ") || echo -n "ERROR - "; \
-		echo "bin/mlkem768_amd64_ref_checksum$$t.out / bin/mlkem768_amd64_avx2_checksum$$t.out"; \
+		(cmp --silent bin/mlkem1024_amd64_avx2_checksum$$t.out bin/pqcrystals_kyber768_ref_checksum$$t.out\  
+		&& echo -n "OK - ") || echo -n "ERROR - "; 
 	done
 
 bin/%.out: bin/%
